# 数据源配置
spring:
    # redis 配置
    redis:
        # Redis开关/默认关闭
        enabled: false
        #cluster:
        #    nodes: 21.1.1.197:6379
        host: 21.1.1.197
        port: 6379
        # 密码
        #password: 123456
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
