# 项目相关配置
itsm:
  # 名称
  name: itsm
  # 版本
  version: 4.5.1
  # 版权年份
  copyrightYear: 2022copyRight 上海银行
  # 用于记录每次生产环境部署的版本号 格式: 1.月份.日期   逐级变更
  appVersion: 1.11.18
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: ${ITSM-PORT:9999}
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    max-connections: 60000
    max-http-post-size: -1
# 支持https访问
# https访问的端口号
https:
  port: 8443
  # 如果证书放在 src/main/resources 下，则需写 classpath:keystore/server.keystore
  ssl:
    key-store: classpath:youi.keystore
    # 证书的签名密码，如果是自己生成的证书在输入信息时会有输入localhost
    key-store-password: youi01
    key-password: youi01
    # 证书类型，常见的两种证书类型有：PKCS12和JKS，这里需要注意证书类型不能写错了，否则项目启动时会报错
    keyStoreType: JKS
    enabled: false
    #DES@[98EEB61DE04A69719DAC0006A80BE343]
# 日志配置
logging:
  level:
    root: info
    com.ruoyi: debug
    # org.springframework: warn
    org.activiti.engine.impl.persistence.entity: info
# Spring配置
spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.177:9200
  data:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    # 241测试环境
    active: app-sit,druid-sit,redis-dev,es-dev
    # UAT环境
    #active: app-uat,druid-uat,redis-uat,es-uat
    # 10.240.140.214测试新环境
#    active: app-sit,druid-sit,redis-dev,es-dev
    # 生产环境
    # active: app-pro,druid-pro,redis-pro,es-pro
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 5GB
      # 设置总上传的文件大小
      max-request-size: 10GB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # activiti 模块
  # 解决启动报错：class path resource [processes/] cannot be resolved to URL because it does not exist
  activiti:
    check-process-definitions: false
    # 检测身份信息表是否存在
    db-identity-used: false
    async-executor-activate: false
    #  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
    database-schema-update: false
# MyBatis
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index

  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString(deskey.getEncoded()));
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 60
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 2
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

knowledge:
  export:
    # 知识库单次查询条数
    num: 8000
    nucleus: 30
#spring boot 监控组件
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

# 长安通讯系统标识开关
cntxtag:
  enabled: true
  zbzbxx: "办公系统值班电话：17601699308 岗位职位职责：终端&网络&应用系统&指挥大厅&1000号呼叫中心  五栋值班电话：15601006476 岗位职责：数据接入&应用系统&云平台运维工作  数字北京值班电话：15601153393、17601029328 岗位职责：硬件&网络&安全" #重保值班信息
sso:
  # 统一门户认证地址
  url: https://20.200.89.83/4a-app/api/authenticate?token=
  token: 56846269b7fd
  clientId: 29PRwwIZvck8waA4MXKT93
  # 统一门户首页跳转地址开关，true-重定向到统一门户登录首页
  portalEnabled: false
  # 统一门户首页跳转地址
  portalIndexUrl: https://20.200.89.83/4a-web
  # 统一门户账号同步接口地址
  portalAccountSyncUrl: https://20.200.89.83:443/4a-app/v1/api/itsmSyncUser/

design:
  standalone:
    enable: false
  datasource:
    enable: false
  file:
    ftp:
        host: 90.18.3.253
        port: 21
        username: ftp
        password: ftp
        path: /design

bizfile:
  prefix: /biz_file
  path: /itsm/itsm/file
  host: http://127.0.0.1:9999
  file_types: [ 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'html', 'htm', 'txt', 'rar', 'gz', 'bz2', 'png', 'jpeg', 'jpg', 'zip', 'pdf', 'gif', 'bmp', 'mp4', 'avi', 'rmvb' ]
  max_file_size: 209715200

vueIndex: http://localhost:10086/#
# 测试环境vue前端页面配置地址
#vueIndex: http://10.240.140.241:18080/#

autoAddress: http://10.240.140.247:8888/
autoUser: ideal
autoPasswd: ideal
